### ISSUE TITLE
std.manifestTomlEx: Output a more minimal form of TOML

### ISSUE THREAD

**Issue by Tatsh** [google/jsonnet#1184]
Do not output extra key headers with no values within:

```toml
[tool]

[tool.item]
key = 1
```

Instead just write:

```toml
[tool.item]
key = 1
```

Also I think `std.manifestToml` should be an alias to Ex with no spaces: `manifestToml(value):: std.manifestTomlEx(value, ''),`
