### ISSUE TITLE
Referencing key id within object?

### ISSUE THREAD

**Issue by ervoiox** [google/jsonnet#319]
Hi there, if I wanted to do something like:

```js
// input
"some-key-1": {
  "name": self.reference.key
}
```

```js
// output
"some-key-1": {
  "name": "some-key-1"
}
```

is there anything that could return the object key of `some-key-1`?

Is the recommended solution to use local?

```
local some_key_1 = "some-key-1",
[some_key_1]: {
  name: [some_key_1]
}
```

I just want have name inferred from the key id.

My keys are static, and wondering if jsonnet can help me not have to duplicate writing the key id inside name again.

Thanks!

**Comment by ant31** [comment]
Hi, 
You can use dict comprehension as you suggested
```yaml
{
  [key]: {name: key} 
  for key in ["key1", "key2", "key3"]
}
```
output:
```yaml
{
   "key1": {
      "name": "key1"
   },
   "key2": {
      "name": "key2"
   },
   "key3": {
      "name": "key3"
   }
}
```
