### ISSUE TITLE
Allow option to use single-quotes instead of double-quotes to wrap YAML KVs

### ISSUE THREAD

**Issue by josdotso** [google/jsonnet#682]
```yaml
---
hello: there
'hi': 'there'
"is": "this okay?"
```
^ This passes `yamllint`.

Would it be agreeable to add an arg to `std.manifestYamlDoc()` and similar functions to emit the `'hi': 'there'` style instead of the `"is": "this okay?"`.  As in jsonnet source code, single quotes are significantly easier to read at scale.
