### ISSUE TITLE
Feature Request: yaml without double quotes (std.manifestYamlDoc)

### ISSUE THREAD

**Issue by Ghost---Shadow** [google/jsonnet#717]
std.manifestYamlDoc generates an yaml like

```yml
"a":"foo"
"b":"bar"
"c":"awesome sauce"
```

which is a valid yaml but it breaks my vscode syntax highlighter.

Can you add a flag which generates like so

```yml
a: foo
b: bar
c: 'awesome sauce'
```

Which is much easier to read IMO
