### ISSUE TITLE
Thoughts on folded text block?

### ISSUE THREAD

**Issue by drewgingerich** [google/jsonnet#915]
This is cross-posted at [google/go-jsonnet](https://github.com/google/go-jsonnet/issues/538).

YAML has folded-style multi-line strings, which means that new-lines are replaced with spaces to end up with a single-line  string. I find this convenient for splitting long shell commands over multiple lines for readability. Does this seem like something potentially good to implement? 

For example and context, I'm looking at using jsonnet to produce YAML Gitlab CI config files. By hand a simplified version looks like this:

```yaml
build:
  stage: build
  only:
    - main
  image: my.kaniko.image
  script:
    - init-kaniko
    - >-
      /kaniko/executor
      --context .
      --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --destination $CI_REGISTRY_IMAGE:latest
```

I really like how I can format the second command in the script block. I think it is very readable and I don't have to fiddle around with escaping new-lines with a `\` like I would in a shell script. I would love to be able to do something similar in jsonnet.

**Comment by sbarzowski** [comment]
Are you aware of `|||` text blocks? See the tutorial: https://jsonnet.org/learning/tutorial.html.

**Comment by sbarzowski** [comment]
Ah, so you want the newlines replaced with spaces. I see how it can be quite useful sometimes.

**Comment by ThatMother1** [comment]
What's up... Alicia's in her world Now with her babies & Family.

**Comment by zc-devs** [comment]
Hi,
I use `>-` [folded style with chomping indicator](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines) for writing CSP headers in Traefik middleware:
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
spec:
  headers:
    contentSecurityPolicy: >-
      upgrade-insecure-requests;
      base-uri 'self';
      default-src 'self';
```
Example above works great.
Recently, I've migrated to Grafana Tanka and that snippet was replaced by:
```
      middlewareHeaders:
        local mw = traefik.middleware;
        mw.new(fullName + '-headers', namespace)
        + mw.metadata.withLabels(labels)
        + mw.spec.headers.withContentSecurityPolicy(|||
          upgrade-insecure-requests;
          base-uri 'self';
          default-src 'self';
        |||),
```
which renders into
```
    contentSecurityPolicy: |
      upgrade-insecure-requests;
      base-uri 'self';
      default-src 'self';
```
While `std.stripChars` can convert `|` to `|-`, it will be multi-line string anyway. Therefore, it doesn't work as HTTP header.
As a workaround I can replace line endings
```
        + mw.spec.headers.withContentSecurityPolicy(std.strReplace(|||
          upgrade-insecure-requests;
          base-uri 'self';
          default-src 'self';
        |||, '\n', ' ')),
```
and it would be rendered as
```
    contentSecurityPolicy: 'upgrade-insecure-requests; base-uri ''self''; default-src
      ''none''; form-action ''none''; frame-ancestors ''none''; '
```
which works, but looks ugly.
So, it would be nice to have ability to render multi-line block as folded YAML, whether it would be addition to`|||` or some standard function.
