### ISSUE TITLE
From a mustache template to jsonnet

### ISSUE THREAD

**Issue by kiryph** [google/jsonnet#979]
### From [Mustache](https://mustache.github.io/mustache.5.html) to jsonnet

I have not yet too much experience with jsonnet. I am trying to convert an [skhd](https://github.com/koekeishiya/skhd) configuration for [yabai](https://github.com/koekeishiya/yabai) generated from a [mustache](https://mustache.github.io/mustache.5.html) template and yaml data file (about 900 lines) to a hopefully more compact jsonnet file.

My mustache file `skhdrc.mustache` is actually not that complicated and uses mustache variables, sections and inverted sections.

<details>
<summary><tt>skhdrc.mustache</tt></summary>

```
# Do not edit this file. Instead edit data.yaml & skhdrc.mustache, then run
# $ mustache data.yaml skhdrc.mustache > skhdrc
# to update this file.

.blacklist [
    "VirtualBoxVM"
]

# ----------------------------------------------------
# skhd keybindings for the tiling window manager Yabai
# ----------------------------------------------------
# https://github.com/koekeishiya/skhd
# https://github.com/koekeishiya/yabai
# Doc: $ man yabai


{{#sections}}
# --------------------
# {{^section_fullname}}{{section_name}}{{/section_fullname}}{{#section_fullname}}{{section_fullname}}{{/section_fullname}}{{#section_modifier}} {{section_modifier.symbol}}{{/section_modifier}}
# --------------------

{{#shortcuts}}
{{#shortcut_cmd}}
# {{shortcut_name}} {{shortcut_modifier.symbol}} {{shortcut_key.symbol}}
{{shortcut_modifier.skhd}} - {{shortcut_key.skhd}} : {{{shortcut_cmd}}}
{{/shortcut_cmd}}
{{/shortcuts}}


{{/sections}}
```
</details>
<details>
<summary>small part of <tt>data.yaml</tt></summary>

```yaml
sections:
  - section_name: "Focus"
    section_modifier: &mod_focus
      <<: *shiftedctrl
    shortcuts:
      - shortcut_name: "Next"
        shortcut_modifier: *mod_focus
        shortcut_key: {symbol: "o", skhd: "o"}
        shortcut_cmd: |
          yabai -m window --focus next
      - shortcut_name: "Previous"
        shortcut_modifier: *mod_focus
        shortcut_key: {symbol: "i", skhd: "i"}
        shortcut_cmd: |
          yabai -m window --focus prev
      - shortcut_name: "Left"
        shortcut_modifier: *mod_focus
        shortcut_key: *west
        shortcut_cmd: |
          yabai -m window --focus west \
          || yabai -m window --focus \
          "$( (yabai -m query --spaces --display west || yabai -m query --spaces --display first) \
          | jq -re '.[] | select(.visible == 1)."last-window"')" \
          || yabai -m window last
      - shortcut_name: "Down"
        shortcut_fullname: "Down or Next"
        shortcut_modifier: *mod_focus
        shortcut_key: *south
        shortcut_cmd: |
          yabai -m window --focus south \
          || yabai -m window --focus next \
          || yabai -m window --focus \
          "$( (yabai -m query --spaces --display next || yabai -m query --spaces --display first) \
          | jq -re '.[] | select(.visible == 1)."first-window"')" \
          || yabai -m window --focus first
      - shortcut_name: "Up"
        shortcut_fullname: "Up or Previous"
        shortcut_modifier: *mod_focus
        shortcut_key: *north
        shortcut_cmd: |
          yabai -m window --focus north \
          || yabai -m window --focus prev \
          || yabai -m window --focus \
          "$( (yabai -m query --spaces --display prev || yabai -m query --spaces --display last) \
          | jq -re '.[] | select(.visible == 1)."last-window"')" \
          || yabai -m window --focus last
```
</details>

I expect an actual advantage of using jsonnet for the yaml file and not for the template file. However, I would like to remove the dependency to mustache when introducing jsonnet.

Before I dive in all the details of my specific situation, I wanted to figure out how to convert the simpler examples on https://mustache.github.io/mustache.5.html to sensible jsonnet constructs.

I have come up with following constructs

```jsonnet
// From https://mustache.github.io/mustache.5.html to https://jsonnet.org

// ❯ jsonnet --version
// Jsonnet commandline interpreter v0.18.0
// ❯ jsonnet -S  -m . mustache.jsonnet

{
  local hash_synopsis = {
    name: 'Chris',
    value: 10000,
    taxed_value: 10000 - (10000 * 0.4),
    in_ca: true,
  },
  // MUSTACHE TEMPLATE:
  // Hello {{name}}
  // You have just won {{value}} dollars!
  // {{#in_ca}}
  // Well, {{taxed_value}} dollars, after taxes.
  // {{/in_ca}}
  'synopsis.txt': |||
    Hello %(name)s
    You have just won %(value)d dollars!
  ||| % hash_synopsis + if hash_synopsis.in_ca then
    'Well, %(taxed_value)d dollars, after taxes' % hash_synopsis,

  local hash_variables = {
    name: 'Chris',
    company: '<b>GitHub</b>',
  },
  // MUSTACHE TEMPLATE:
  // * {{name}}
  // * {{age}}
  // * {{company}}
  // * {{{company}}}
  'variables.txt': |||
    * %(name)s
    * %(age)s
    * %(company)s
    * %(company)s
  ||| % {
    name: hash_variables.name,
    age: if std.objectHas(hash_variables, 'age') then '%(age)d' % hash_variables else '',
    company: hash_variables.company,
  },
  // if there are no missing values, a more compact % hash_variables can be used.
  // Upcoming std.get(hash_variables, 'age', default='')
  // TODO missing escapeStringHTML similar to {{{ }}} or {{% name}} of mustache

  local hash_sections = {
    person: false,
  },
  // MUSTACHE TEMPLATE:
  // Shown.
  // {{#person}}
  //   Never shown!
  // {{/person}}
  'sections.txt': |||
    Shown.
  ||| + if hash_sections.person then
    'Never shown!' else '',

  local hash_non_empty_lists = {
    repo: [
      { name: 'resque' },
      { name: 'hub' },
      { name: 'rip' },
    ],
  },
  // MUSTACHE TEMPLATE:
  // {{#repo}}
  //   <b>{{name}}</b>
  // {{/repo}}
  'non-empty_lists.txt':
    std.lines([
      '<b>' + x.name + '</b>'
      for x in hash_non_empty_lists.repo
    ]),

  local hash_non_false_values = {
    'person?': { name: 'Jon' },
  },
  // MUSTACHE TEMPLATE:
  // {{#person?}}
  //   Hi {{name}}!
  // {{/person?}}
  'non-false_values.txt': if hash_non_false_values['person?'] != null then
    'Hi %(name)s!' % hash_non_false_values['person?']
  else
    '',

  local hash_inverted_sections = {
    repo: [],
  },
  // MUSTACHE TEMPLATE:
  // {{#repo}}
  //   <b>{{name}}</b>
  // {{/repo}}
  // {{^repo}}
  //   No repos :(
  // {{/repo}}
  'inverted-sections.txt':
    std.lines([
      '<b>' + x.name + '</b>'
      for x in hash_inverted_sections.repo
    ]) + if std.length(hash_inverted_sections.repo) == 0 then
      'No repos :(',
}
```

Most constructs are longer or syntactically more complicated and an `std.escapeStringHTML` does not exist in jsonnet. However, this is not important for me as long as the actual data part becomes shorter. The bulky `data.yaml` file is the motivation to switch to jsonnet and not the template part. But this does not mean that I do not want to write an elegant jsonnet code for the file generation.

Can someone else have a look at this and point out improvements of the jsonnet constructs if applicable or share their thoughts on this? Thank you.
